spring:
  application:
    name: blogger-box-backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-gentle-leaf-a22z8pqd.eu-central-1.aws.neon.tech:5432/blogger
    username: blogger_owner
    password: xZob3k6fKwXe

  jpa:
    hibernate.ddl-auto: validate
    show-sql: false

server:
  port: 8080
